import type { Metadata } from "next";
import "../globals.css";
import NavBar from "../components/sims-app/navbar";
import ReduxProvider from "../state/redux-provider";
import { Toaster } from "react-hot-toast";

export const metadata: Metadata = {
  title: "SIMS PPOB James Limantara",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/Logo.png" type="image/x-icon" />
        <style>
          @import url(&apos;https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap&apos;);
        </style>
      </head>
      <body
        className={`font-body font-display antialiased`}
      >
        <ReduxProvider>
          <header>
            <NavBar/>
          </header>
            {children}
          <Toaster/>
        </ReduxProvider>
      </body>
    </html>
  );
}
